#base-url =  https://restful-booker.herokuapp.com/

base-url = https://automationexercise.com
product-list = api/productsList
brand-list = api/brandsList
verify-user= api/verifyLogin
search-product = api/searchProduct
create-account= api/createAccount
delete-account = api/deleteAccount
update-user = api/updateAccount
search-by-email = api/getUserDetailByEmail
